export interface Tool {
  id: string;
  name: string;
  description: string;
  category: "image" | "pdf" | "text" | "calculator";
  path: string;
  keywords: string[];
  isPopular?: boolean;
  isTrending?: boolean;
  isRecent?: boolean;
}

export const CATEGORIES = {
  image: {
    name: "Image Tools",
    description: "Compress, resize, crop, rotate, and convert formats with client-side privacy-first image processors.",
    path: "/image-tools",
    icon: "Image",
    color: "from-blue-500 to-indigo-500",
  },
  pdf: {
    name: "PDF Utilities",
    description: "Unlock, merge, split, rotate, watermark, and convert documents locally in your browser.",
    path: "/pdf-tools",
    icon: "FileText",
    color: "from-red-500 to-rose-500",
  },
  text: {
    name: "Text Analyzers",
    description: "Case converters, duplicate removers, formatters, validators, and encoders for developer tasks.",
    path: "/text-tools",
    icon: "Type",
    color: "from-emerald-500 to-teal-500",
  },
  calculator: {
    name: "Calculators",
    description: "EMI, GST, Age, Loan, BMI, SIP, and Scientific calculators with step-by-step formula explanations.",
    path: "/calculators",
    icon: "Calculator",
    color: "from-amber-500 to-orange-500",
  },
};

export const TOOLS: Tool[] = [
  // --- Image Tools ---
  {
    id: "img-compress",
    name: "Compress Image",
    description: "Reduce image file size with adjustable compression level and side-by-side live comparison.",
    category: "image",
    path: "/image-tools/compress",
    keywords: ["compress image", "shrink jpg", "reduce png size", "image optimizer"],
    isPopular: true,
  },
  {
    id: "img-resize",
    name: "Resize Image",
    description: "Change image dimensions in pixels, maintaining aspect ratio or custom sizing.",
    category: "image",
    path: "/image-tools/resize",
    keywords: ["resize image", "image dimensions", "scale image px", "resize height width"],
  },
  {
    id: "img-convert",
    name: "Convert Image Format",
    description: "Convert images seamlessly between JPG, PNG, WEBP, GIF, BMP, and SVG.",
    category: "image",
    path: "/image-tools/convert",
    keywords: ["convert format", "jpg to png", "png to webp", "image converter"],
    isPopular: true,
    isTrending: true,
  },
  {
    id: "img-bg-remover",
    name: "Background Remover",
    description: "Click to remove background color and generate transparent PNGs instantly.",
    category: "image",
    path: "/image-tools/bg-remover",
    keywords: ["remove background", "transparent png maker", "delete image backdrop", "chroma key canvas"],
    isTrending: true,
  },
  {
    id: "img-crop",
    name: "Crop Image",
    description: "Trim image boundaries with an interactive canvas selector.",
    category: "image",
    path: "/image-tools/crop",
    keywords: ["crop photo", "cut image borders", "trim picture px"],
  },
  {
    id: "img-rotate",
    name: "Rotate & Flip",
    description: "Rotate images 90 degrees or mirror them horizontally and vertically.",
    category: "image",
    path: "/image-tools/rotate",
    keywords: ["rotate image", "flip image", "mirror photograph", "90 degree turn"],
  },
  {
    id: "img-watermark",
    name: "Add Watermark",
    description: "Overlay custom text or logos onto your images with transparency settings.",
    category: "image",
    path: "/image-tools/watermark",
    keywords: ["watermark photo", "copyright logo", "text stamp image"],
  },
  {
    id: "img-to-pdf",
    name: "Image to PDF",
    description: "Pack JPG, PNG, or WEBP images into a clean multi-page PDF document.",
    category: "image",
    path: "/image-tools/image-to-pdf",
    keywords: ["jpg to pdf converter", "images to pdf document", "compile graphics to pdf"],
  },
  {
    id: "pdf-to-image",
    name: "PDF to Image",
    description: "Extract pages of a PDF document and save them as individual JPEG images.",
    category: "image",
    path: "/image-tools/pdf-to-image",
    keywords: ["pdf to jpg", "pdf to png", "extract pdf slides", "save pdf pages as images"],
  },

  // --- PDF Tools ---
  {
    id: "pdf-unlock",
    name: "PDF Password Unlocker",
    description: "Remove security password locks from your PDF files to decrypt them permanently.",
    category: "pdf",
    path: "/pdf-tools/unlock",
    keywords: ["unlock pdf", "remove pdf password", "decrypt pdf file", "pdf restriction remover"],
    isPopular: true,
  },
  {
    id: "pdf-merge",
    name: "Merge PDF Documents",
    description: "Combine multiple PDF files into a single consolidated PDF document.",
    category: "pdf",
    path: "/pdf-tools/merge",
    keywords: ["merge pdfs", "join pdf", "combine pages document"],
    isTrending: true,
  },
  {
    id: "pdf-split",
    name: "Split PDF Pages",
    description: "Extract specific pages or ranges from a PDF file into new individual documents.",
    category: "pdf",
    path: "/pdf-tools/split",
    keywords: ["split pdf", "extract page range", "cut pdf pages"],
  },
  {
    id: "pdf-compress",
    name: "Compress PDF Size",
    description: "Reduce PDF document file size while preserving layout structure.",
    category: "pdf",
    path: "/pdf-tools/compress",
    keywords: ["shrink pdf size", "compress pdf mb to kb", "pdf file optimizer"],
  },
  {
    id: "pdf-to-word",
    name: "PDF to Word Converter",
    description: "Extract text from PDF layouts into editable Word document compatibility format.",
    category: "pdf",
    path: "/pdf-tools/pdf-to-word",
    keywords: ["pdf to docx", "convert pdf to word", "editable document layout"],
  },
  {
    id: "word-to-pdf",
    name: "Word to PDF",
    description: "Convert standard written text or layout templates directly into a PDF document.",
    category: "pdf",
    path: "/pdf-tools/word-to-pdf",
    keywords: ["docx to pdf", "convert docx", "document compilation"],
  },
  {
    id: "pdf-to-jpg",
    name: "PDF to JPG",
    description: "Quick extraction tool converting all pages inside a PDF into a high-res zip of JPGs.",
    category: "pdf",
    path: "/pdf-tools/pdf-to-jpg",
    keywords: ["convert pdf to jpg", "pdf images extract"],
  },
  {
    id: "jpg-to-pdf",
    name: "JPG to PDF",
    description: "Convert custom photo collections into a clean, combined single PDF file.",
    category: "pdf",
    path: "/pdf-tools/jpg-to-pdf",
    keywords: ["compile jpg to pdf", "photos to pdf document"],
  },
  {
    id: "pdf-rotate",
    name: "Rotate PDF Pages",
    description: "Rotate select pages inside a PDF document to landscape or portrait alignment.",
    category: "pdf",
    path: "/pdf-tools/rotate",
    keywords: ["rotate pdf", "turn pdf page", "landscape portrait orientation"],
  },
  {
    id: "pdf-watermark",
    name: "Add PDF Watermark",
    description: "Staple custom text labels across pages of a PDF to mark draft or proprietary statuses.",
    category: "pdf",
    path: "/pdf-tools/watermark",
    keywords: ["watermark pdf", "confidential stamp pdf", "add copyright text to document"],
  },

  // --- Text Tools ---
  {
    id: "text-case-converter",
    name: "Text Case Converter",
    description: "Change writing formats instantly: UPPERCASE, lowercase, Title Case, Sentence Case, or camelCase.",
    category: "text",
    path: "/text-tools/case-converter",
    keywords: ["case converter", "uppercase lowercase", "title case generator", "sentence cap"],
  },
  {
    id: "text-remove-duplicates",
    name: "Remove Duplicate Lines",
    description: "Filter out redundant rows of text to create unique lists instantly.",
    category: "text",
    path: "/text-tools/remove-duplicates",
    keywords: ["remove duplicates", "unique lines list", "clean repeating rows"],
  },
  {
    id: "text-word-counter",
    name: "Word & Character Counter",
    description: "Live word count, character count, sentence tally, paragraph metrics, and estimated reading time.",
    category: "text",
    path: "/text-tools/word-counter",
    keywords: ["word counter", "character count", "letter length checker", "reading time index"],
    isPopular: true,
  },
  {
    id: "text-line-sorter",
    name: "Line Sorter",
    description: "Alphabetize rows of text or sort them numerically in ascending or descending sequence.",
    category: "text",
    path: "/text-tools/line-sorter",
    keywords: ["sort lines", "alphabetize list", "numerical sorting rows"],
  },
  {
    id: "text-json-formatter",
    name: "JSON Formatter & Validator",
    description: "Prettify nested JSON inputs, validate syntax, and pinpoint parse errors with line numbers.",
    category: "text",
    path: "/text-tools/json-formatter",
    keywords: ["json formatter", "json validator", "prettify json", "fix json parser"],
    isPopular: true,
  },
  {
    id: "text-xml-formatter",
    name: "XML Formatter",
    description: "Prettify markup files, clean nesting, indent, and format raw XML strings.",
    category: "text",
    path: "/text-tools/xml-formatter",
    keywords: ["xml formatter", "xml prettify", "indent tags xml"],
  },
  {
    id: "text-base64",
    name: "Base64 Encoder & Decoder",
    description: "Securely encode standard text to Base64 binaries, or translate hashes back to text.",
    category: "text",
    path: "/text-tools/base64",
    keywords: ["base64 encoder", "base64 decoder", "hash translate text"],
  },
  {
    id: "text-url",
    name: "URL Encoder & Decoder",
    description: "Parse special characters in query parameters into URL percent-encodings and back.",
    category: "text",
    path: "/text-tools/url",
    keywords: ["url encode", "url decode", "uri percent parser"],
  },
  {
    id: "text-reverser",
    name: "Text Reverser",
    description: "Flip characters, words, or full lines upside down or backwards for fun or cryptography.",
    category: "text",
    path: "/text-tools/reverser",
    keywords: ["reverse text", "flip characters backwards", "mirror lettering"],
  },
  {
    id: "text-lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate mock copy paragraphs, sentences, or bulleted lists for designers.",
    category: "text",
    path: "/text-tools/lorem-ipsum",
    keywords: ["lorem ipsum generator", "dummy text placeholder", "placeholder paragraph generator"],
  },
  {
    id: "text-regex",
    name: "Regex Tester",
    description: "Live test regex expressions against strings with full highlighted matching scopes.",
    category: "text",
    path: "/text-tools/regex",
    keywords: ["regex tester", "regular expression checker", "match capture group regex"],
  },
  {
    id: "text-html-encoder",
    name: "HTML Entities Encoder",
    description: "Translate special HTML markup tokens into safe entity codes to prevent rendering.",
    category: "text",
    path: "/text-tools/html-encoder",
    keywords: ["html encode", "html entities", "escape xml characters"],
  },
  {
    id: "text-markdown",
    name: "Markdown Previewer",
    description: "Live edit Markdown formatting side-by-side with rendered HTML layout visualization.",
    category: "text",
    path: "/text-tools/markdown",
    keywords: ["markdown previewer", "render markdown md", "live edit rich text html"],
  },
  {
    id: "text-diff",
    name: "Diff Checker",
    description: "Highlight visual differences between Text A and Text B (red deletions, green additions).",
    category: "text",
    path: "/text-tools/diff",
    keywords: ["diff checker", "text difference compare", "find variations file text"],
    isTrending: true,
  },
  {
    id: "text-find-replace",
    name: "Find & Replace",
    description: "Scan inputs to replace matching strings with custom overrides, using casing rules.",
    category: "text",
    path: "/text-tools/find-replace",
    keywords: ["find replace", "substitute words text", "swap matching terms"],
  },
  {
    id: "text-remove-spaces",
    name: "Remove Extra Spaces",
    description: "Clean up trailing, double, or tabs-based spaces in paragraphs to standardize texts.",
    category: "text",
    path: "/text-tools/remove-spaces",
    keywords: ["remove extra spaces", "clean blank whitespace", "trim sentence tabs"],
  },
  {
    id: "text-slugify",
    name: "Text to Slug Converter",
    description: "Convert page titles to search-friendly, clean SEO URL slugs (lowercase, hyphenated).",
    category: "text",
    path: "/text-tools/slugify",
    keywords: ["text to slug", "slugify url generator", "seo path clean string"],
  },
  {
    id: "text-keyword-density",
    name: "Keyword Density Checker",
    description: "Analyze word frequencies to highlight keyword saturation and density percentages.",
    category: "text",
    path: "/text-tools/keyword-density",
    keywords: ["keyword density", "word frequency count", "seo keyword stuffing index"],
  },

  // --- Calculators ---
  {
    id: "calc-scientific",
    name: "Scientific Calculator",
    description: "Complete browser-based scientific calculator with trigonometric, logarithmic, and history functions.",
    category: "calculator",
    path: "/calculators/scientific",
    keywords: ["scientific calculator", "advanced math calculation", "sin cos tan calculator", "log arithmetic"],
    isPopular: true,
  },
  {
    id: "calc-bmi",
    name: "BMI Calculator",
    description: "Compute your Body Mass Index (BMI) instantly based on weight and height metrics.",
    category: "calculator",
    path: "/calculators/bmi",
    keywords: ["bmi calculator", "body mass index rating", "ideal weight metric healthy"],
  },
  {
    id: "calc-emi",
    name: "EMI Calculator",
    description: "Calculate Equated Monthly Installments (EMIs) with detailed loan interest distributions.",
    category: "calculator",
    path: "/calculators/emi",
    keywords: ["emi calculator", "monthly installment interest", "repayment schedule math"],
    isPopular: true,
  },
  {
    id: "calc-gst",
    name: "GST Calculator",
    description: "Add or remove Goods and Services Tax (GST) from amounts using custom rates.",
    category: "calculator",
    path: "/calculators/gst",
    keywords: ["gst calculator", "tax add subtract calculation", "net gross invoice calculator"],
  },
  {
    id: "calc-age",
    name: "Age Calculator",
    description: "Compute exact age in years, months, days, minutes, and seconds from a birth date.",
    category: "calculator",
    path: "/calculators/age",
    keywords: ["age calculator", "how old am i", "calculate birthday duration"],
    isTrending: true,
  },
  {
    id: "calc-sip",
    name: "SIP Investment Calculator",
    description: "Simulate compound interest returns from periodic mutual fund Systematic Investment Plans.",
    category: "calculator",
    path: "/calculators/sip",
    keywords: ["sip calculator", "mutual fund growth compound", "future returns projection"],
    isTrending: true,
  },
  {
    id: "calc-loan",
    name: "Loan Calculator",
    description: "Estimate overall interest payables and compound principal schedules for home/car loans.",
    category: "calculator",
    path: "/calculators/loan",
    keywords: ["loan calculator", "amortization chart principal", "loan duration calculator"],
  },
  {
    id: "calc-discount",
    name: "Discount Calculator",
    description: "Quick price calculator showing savings value and final sale price for retail purchases.",
    category: "calculator",
    path: "/calculators/discount",
    keywords: ["discount calculator", "sale percent savings", "original price calculation"],
  },
];
